AppBundle\Entity\Offer:
  type: entity
  table: offer
  id:
      id:
          type: integer
          generator:
              strategy: AUTO
  fields:
      title:
          type: string
          lenght: 80
          nullable: false
          column: title
      description:
          type: string
          lenght: 255
          nullable: false
          column: description
      email:
          type: string
          lenght: 80
          nullable: false
          unique: true
          column: email
      image:
          type: string
          lenght: 255
          nullable: false
          column: image
      createdAt:
          type: date
          lenght: 10
          nullable: false
          column: created_at

